import { poppins, roboto } from '@/components/assets/fontes'
import RaizHeader from '@/components/layout/header/raiz-header'
import type { Metadata } from 'next'
import '../styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body
        className={`min-h-screen bg-zinc-950 font-sans antialiased ${poppins.variable}  ${roboto.variable}`}
      >
        <RaizHeader />
        {children}
      </body>
    </html>
  )
}
